version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_ping
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pinger:
    build: ./pinger
    restart: always
    depends_on:
      - db
    tty: true
    stdin_open: true

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

#  frontend:
#    build: ./frontend
#    ports:
#      - "3000:80"
#    depends_on:
#      - backend